FROM node:lts-alpine
RUN mkdir -p /base/apps/auth
RUN mkdir -p /base/build/apps/auth
WORKDIR /base/apps/auth
ENV NODE_ENV=dev
COPY ./apps/auth /base/apps/auth
COPY package.json /base
COPY tsconfig.base.json /base
COPY ./apps/auth/.env.dev /base/build/apps/auth
RUN npm install
RUN npm run build:auth
EXPOSE 3000
CMD ["npm", "run", "start:auth"]
